### ISSUE TITLE
File.exists? is deprecated (ruby 2.1.0)

### ISSUE THREAD

**Issue by mclang** [samullen/pidfile#2]
I get following warning when using pidfile gem with Ruby v2.1.0:
/usr/local/rvm/gems/ruby-2.1.0/gems/pidfile-0.3.0/lib/pidfile.rb:109: warning: File.exists? is a deprecated name, use File.exist? instead

I know how to fix that (fork & pull request), put how does this possible fix get into RubyGems so that I get in when installing the gem?

I ask this also because, it seems I still have the old version where default pidfile directory is /tmp instead of /var/run.

**Comment by samullen** [comment]
I really don't maintain this anymore (for several years now). The Rakefile needs to be rewritten and everything moved up to Ruby 2.1 and I just don't have the time.

I'm more than happy to take pull requests, and hand over ownership to someone else though.

**Comment by mclang** [comment]
Yeah, I read what you replied to rehevkor5. He seemed willing to take over this... Have You been in contact with him lately?

This seems to be such a simple gem to maintain that I could try also... But I don't have any experience about making ruby gems or taking ownership of git project :(

**Comment by mclang** [comment]
Hello
I forked your pidfile repo and fixed things. Then I tried to follow RubyGems guide:
http://guides.rubygems.org/make-your-own-gem/

Couple of questions:
- How to do 'gem build' b/c there is no 'pidfile.gemspec'? I found the same kind of definition from Rakefile, but couldn't get it to work.
- If you give the ownership of this gem to me, how can I replace your older pidfile version in RubyGems with my newer one?

I'm terribly sorry if these question are stupid but I couldn't find answers from RubyGems guide :(

**Comment by samullen** [comment]
Hey, MC. I want to get back and fix this, but I'm swamped with client work at the moment. I'm more than happy to work with you to get the gem up and running. Like I said, this is pretty old and a lot of things have changed since I first wrote it. The problems you're seeing are likely due to the version of Ruby you're running. I probably wrote this under 1.8.x.

I'm even willing to work with you to get the gem up and running on the version of Ruby you're using, but I just don't have availability yet. So give me a week or two to get into my summer routine and we'll set aside an hour or two to update the gem for ruby 2.x. In the meantime, use your local copy if you can.

**Comment by mclang** [comment]
No problem!
Let's do this when You have sorted more important things out... Meanwhile I can use the old version, the warning doesn't break anything.
